_inputs:
  enclosure: 
    type: text 
    comment: "URL of media file. Example: https://example.com/podcast.mp4"
  enclosure_type:
    type: text
    comment: "MIME type of media file. Possible values: audio/x-m4a, audio/mpeg, video/quicktime, video/mp4, video/x-m4v, and application/pdf"
  enclosure_time:
    type: text
    comment: "File size in bytes. Example: 5650889"
  title:
    type: text
    label: Page title
  subtitle:
    type: text
    label: Subtitle

_snippets:
  jekyll_include:
    snippet: '{% include [[include_name]] %}'
    preview:
      text:
        - template: 'Include {name_of_include}'
        - 'Include'
    _inputs:
      name_of_include:
        type: disabled
    params:
      include_name:
        parser: argument
        options:
          model:
            editor_key: name_of_include
          format:
            string_boundary:
              - ''
            forbidden_tokens:
              - '%'

collections_config:
  pages:                # keep pages in the site root
    path: /
    _enabled_editors: [visual, data]
    schemas:
      custom:
        name: Custom Page
        path: .cloudcannon/schemas/custom_page.md
    preview:
      text:
        - key: title